# Generated by Django 2.2 on 2019-07-14 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='Заголовок')),
                ('kindOfDish', models.CharField(default=None, max_length=100, verbose_name='Категория блюда')),
                ('kindOfMeat', models.CharField(default=None, max_length=100, null=True)),
                ('kindOfFish', models.CharField(default=None, max_length=100, null=True)),
                ('ingredients', models.TextField(default='default', null=True, verbose_name='Ингредиенты')),
                ('instruction', models.TextField(default='default', null=True, verbose_name='Инструкция')),
                ('description', models.TextField(default='default', null=True, verbose_name='Примечание')),
                ('level', models.CharField(default=None, max_length=100, verbose_name='Уровень сложности')),
                ('oursForCooking', models.IntegerField(default=None, verbose_name='Час(ов)')),
                ('minutsForCooking', models.IntegerField(default=None, verbose_name='Минут(ы)')),
                ('img', models.ImageField(upload_to='recipes/static/recipes/img/', verbose_name='Изображение')),
                ('country', models.CharField(default=None, max_length=100, verbose_name='Происхождение')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата публикации')),
                ('moderation', models.CharField(choices=[('S', 'SPAM'), ('N', 'Not Moderated'), ('P', 'Post Moderated'), ('M', 'Moderated')], default='N', max_length=1, verbose_name='Модерация')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
