# Generated by Django 2.2 on 2019-07-08 12:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VeganDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'VeganDish',
            },
        ),
        migrations.CreateModel(
            name='MeatDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('ingredients', models.TextField()),
                ('cookingDescription', models.TextField()),
                ('cookingDifficulty', models.CharField(choices=[('L1', 'Уровень 1'), ('L2', 'Уровень 2'), ('L3', 'Уровень 3')], max_length=100)),
                ('preparationTime', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/recipes/img/')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.date(2019, 7, 8), null=True, verbose_name='Дата публикации')),
                ('moderation', models.CharField(choices=[('S', 'SPAM'), ('N', 'Not Moderated'), ('P', 'Post Moderated'), ('M', 'Moderated')], default='N', max_length=1, verbose_name='Модерация')),
                ('kindOfMeat', models.CharField(choices=[('CHICKEN', 'Курица'), ('COW', 'Говядина'), ('PIG', 'Свинина'), ('RAM', 'Баранина'), ('VEAL', 'Телятина'), ('TURTLE', 'Черепаха')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Country')),
            ],
            options={
                'db_table': 'MeatDish',
            },
        ),
        migrations.CreateModel(
            name='FishDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('ingredients', models.TextField()),
                ('cookingDescription', models.TextField()),
                ('cookingDifficulty', models.CharField(choices=[('L1', 'Уровень 1'), ('L2', 'Уровень 2'), ('L3', 'Уровень 3')], max_length=100)),
                ('preparationTime', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/recipes/img/')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.date(2019, 7, 8), null=True, verbose_name='Дата публикации')),
                ('moderation', models.CharField(choices=[('S', 'SPAM'), ('N', 'Not Moderated'), ('P', 'Post Moderated'), ('M', 'Moderated')], default='N', max_length=1, verbose_name='Модерация')),
                ('kindOfFish', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Country')),
            ],
            options={
                'db_table': 'FishDish',
            },
        ),
    ]
